{% set name = "pygadm" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygadm-{{ version }}.tar.gz
  sha256: 2f2491138258793eddfd6db44c296cd92eb342bc9e24c4f4f85fa5d37917ea76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - deprecated
    - geopandas
    - pyarrow
    - requests-cache

test:
  imports:
    - pygadm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygadm/
  summary: Easy access to administrative boundary defined by GADM from Python scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 12rambau
