{% set name = "pygadm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygadm-{{ version }}.tar.gz
  sha256: 949faf748c8d6052caaeeeda71854cd410daaf19c3c7ac76e6de844202dd37e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - deprecated
    - geopandas
    - pyarrow

test:
  imports:
    - pygadm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygadm/
  summary: Easy access to administrative boundary defined by GADM from Python scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 12rambau
